run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - deadcode
    - gofmt
issues:
  exclude-rules:
    - path: "_test\\.go"
      text: "Error return value is not checked"
