name: Update CHANGELOG

# Dispara quando uma Release é publicada.
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # precisamos de permissão para commitar de volta
          persist-credentials: true

      - name: Generate CHANGELOG.md from release notes
        run: |
          TAG=${{ github.event.release.tag_name }}
          gh release view "$TAG" --json body --jq .body > CHANGELOG.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push CHANGELOG.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for $TAG" || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
