# CI / CD Pipeline for netcalc
name: CI / CD Pipeline

# Trigger on pushes to main or master, version tags, or manual dispatch
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  workflow_dispatch:

# Grant GitHub token write permissions for releases
permissions:
  contents: write

jobs:
  # ---------------------------------------------------------------------------
  # Lint job: validate code style and static analysis
  # ---------------------------------------------------------------------------
  lint:
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

  # ---------------------------------------------------------------------------
  # Test job: execute unit tests and upload coverage
  # ---------------------------------------------------------------------------
  test:
    if: "!startsWith(github.ref, 'refs/tags/')"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run tests
        run: go test ./... -v

      - name: Generate coverage
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Opcional se o repo for público
          files: coverage.out
          fail_ci_if_error: true

  # ---------------------------------------------------------------------------
  # Build job: cross-compile binaries for multiple platforms
  # ---------------------------------------------------------------------------
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Cross-compile binary
        run: |
          # Determine target OS based on matrix value
          GOOS=$(
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              echo windows
            elif [ "${{ matrix.os }}" = "macos-latest" ]; then
              echo darwin
            else
              echo linux
            fi
          )
          GOARCH=${{ matrix.arch }}
          # Build with version metadata via ldflags
          go build \
            -ldflags="-X main.buildTime=$(date -u '+%Y-%m-%dT%H:%M:%SZ') \
                      -X main.gitCommit=$(git rev-parse --short HEAD) \
                      -X main.gitBranch=$(git rev-parse --abbrev-ref HEAD')" \
            -o "bin/${{ matrix.os }}_${{ matrix.arch }}/netcalc${{ matrix.os == 'windows-latest' && '.exe' || '' }}" \
            netcalc.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: netcalc-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/${{ matrix.os }}_${{ matrix.arch }}/

  # ---------------------------------------------------------------------------
  # Release job: create GitHub release on new tag
  # ---------------------------------------------------------------------------
  release-on-tag:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/windows-latest_amd64/netcalc.exe
          asset_name: netcalc-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/ubuntu-latest_amd64/netcalc
          asset_name: netcalc-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS AMD64 artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/macos-latest_amd64/netcalc
          asset_name: netcalc-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/macos-latest_arm64/netcalc
          asset_name: netcalc-macos-arm64
          asset_content_type: application/octet-stream
