name: CI Pipeline - Build, Test & Deploy.
description: "Workflow to generate and automatically update CHANGELOG.md when a release is published"

on:
  release:
    types: [ published ]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMIT_USER: "github-actions[bot]"
  COMMIT_EMAIL: "actions@github.com"

jobs:
  update-changelog:
    name: Update CHANGELOG
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ env.COMMIT_USER }}"
          git config user.email "${{ env.COMMIT_EMAIL }}"

          # Make sure we are on the correct branch (replace master if main)
          git fetch origin master
          git checkout master
          git pull origin master

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Generate CHANGELOG.md from the release
        run: |
          TAG=${{ github.event.release.tag_name }}
          gh release view "$TAG" --json body --jq .body > CHANGELOG.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md

          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "docs: update CHANGELOG for ${{ github.event.release.tag_name }}"
            git push origin master
          else
            echo "No changes to commit"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}