name: CI/CD Pipeline

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

env:
  # Versões e Configurações
  GO_VERSION: '1.20'
  GIT_USER: "github-actions[bot]"
  GIT_EMAIL: "actions@github.com"
  # Autenticação
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and Test
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-verify-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  update-changelog:
    name: Update Changelog
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name "${GIT_USER}"
          git config user.email "${GIT_EMAIL}"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Generate and update CHANGELOG.md
        run: |
          TAG=${{ github.event.release.tag_name }}
          PREV_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | grep -v "$TAG" | head -n1 || echo "")
          echo "## ${TAG} - $(date -u +%Y-%m-%d)" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "**Release Notes:**" >> CHANGELOG.md
          gh release view "$TAG" --json body --jq .body | sed 's/^/  /' >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          if [[ -n "$PREV_TAG" ]]; then
            echo "**Commits since ${PREV_TAG}:**" >> CHANGELOG.md
            git log "${PREV_TAG}...${TAG}" --pretty=format:"- %s (%an)" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

      - name: Commit and push CHANGELOG.md
        run: |
          git add CHANGELOG.md
          # Stash changes, keep index
          git stash push --keep-index -m "changelog-stash"
          # Pull latest changes from main
          git pull origin main
          # Restore stash
          git stash pop || true
          if ! git diff --staged --quiet; then
            git commit --author="Release Bot <noreply@github.com>" -m "docs(changelog): update for ${TAG}"
            git push origin main
          fi

  deploy-production:
    name: Deploy to Production
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    needs: build-and-test
    env:
      GITHUB_REPO: ${{ github.repository }}
      REP_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          chmod +x ./deploy.py
          ./deploy.py \
            --build \
            --test \
            --commit "ci: implantação em produção" \
            --tag "release-${{ github.run_number }}"
